#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Time-stamp: <2025-05-04 19:02:42 krylon>
#
# %filename%
# created on %date%
# (c) %year% %author%
#
# This file is part of mesopotamia. It is distributed under the terms
# of the GNU General Public License 3. See the file LICENSE for
# details or find a copy online at
# https://www.gnu.org/licenses/gpl-3.0

"""
mesopotamia.%lmodule%

(c) %year% %author%
"""

# Local Variables: #
# python-indent: 4 #
# End: #
